pipeline:
  name: test-ember
  identifier: testember
  projectIdentifier: NgLabs
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitconnectordhruba
        repoName: ember.js
        build: <+input>
  stages:
    - stage:
        name: lint
        identifier: lint
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: Checkout
                  identifier: Checkout
                  spec:
                    uses: actions/checkout@v3
              - step:
                  type: Action
                  name: Setup node
                  identifier: Setup_node
                  spec:
                    uses: actions/setup-node@v3
                    with:
                      node-version: 14.x
                      cache: yarn
              - step:
                  type: Run
                  name: install dependencies
                  identifier: install_dependencies
                  spec:
                    shell: Sh
                    command: yarn install --frozen-lockfile --non-interactive
              - step:
                  type: Run
                  name: linting
                  identifier: linting
                  spec:
                    shell: Sh
                    command: yarn lint
    - stage:
        name: Type Checking
        identifier: Type_Checking
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: Checkout
                  identifier: Checkout
                  spec:
                    uses: actions/checkout@v3
              - step:
                  type: Action
                  name: Setup node
                  identifier: Setup_node
                  spec:
                    uses: actions/setup-node@v3
                    with:
                      node-version: 14.x
                      cache: yarn
              - step:
                  type: Run
                  name: install dependencies
                  identifier: install_dependencies
                  spec:
                    shell: Sh
                    command: yarn install --frozen-lockfile --non-interactive
              - step:
                  type: Run
                  name: Check published types
                  identifier: Check_published_types
                  spec:
                    shell: Sh
                    command: yarn type-check:types
    - stage:
        name: Debug and Prebuilt
        identifier: Debug_and_Prebuilt
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: Checkout
                  identifier: Checkout
                  spec:
                    uses: actions/checkout@v3
              - step:
                  type: Action
                  name: Setup node
                  identifier: Setup_node
                  spec:
                    uses: actions/setup-node@v3
                    with:
                      node-version: 14.x
                      cache: yarn
